Fix exit status aggregation in lazy tests run

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -74,7 +74,7 @@ jobs:
             for demo in !($IGNORED_DIRS); do
               if [ -d "$demo" ]; then
                 declare -i pid test_status=255
-                
+
                 # run tests for this demo in bg
                 # subshell exits on first error
                 (
@@ -85,7 +85,7 @@ jobs:
                   echo "$demo"
                   coverage run -m unittest discover
                 ) & pid=$!
-                
+
                 # wait for tests to finish, collecting the exit status
                 # of the first failing command in the subshell
                 while (( test_status > 128 )); do
@@ -93,10 +93,11 @@ jobs:
                 done
 
                 # accumulate test status
-                (( job_status |= test_status ))
+                # (don't fail for zero results in bash -e mode)
+                (( job_status |= test_status )) || true
               fi
             done
-            
+
             exit $job_status
 
   test-3.6:
