Fix lazy tests fail

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -68,20 +68,36 @@ jobs:
             # Loop through unit tests
             # Note: failed unit tests are skipped. Return the last failed unit
             #   test exit code once the loop completes.
-            exit_code=0
+
+            declare -i job_status=0
+
             for demo in !($IGNORED_DIRS); do
               if [ -d "$demo" ]; then
-                env="envs/$demo"
-                . "$env/bin/activate"
+                declare -i pid test_status=255
+                
+                # run tests for this demo in bg
+                # subshell exits on first error
+                (
+                  env="envs/$demo"
+                  . "$env/bin/activate"
 
-                cd "$demo"
-                echo "$demo"
-                coverage run -m unittest discover || exit_code=$?
-                cd ..
+                  cd "$demo"
+                  echo "$demo"
+                  coverage run -m unittest discover
+                ) & pid=$!
+                
+                # wait for tests to finish, collecting the exit status
+                # of the first failing command in the subshell
+                while (( test_status > 128 )); do
+                    wait $pid || test_status=$?
+                done
+
+                # accumulate test status
+                (( job_status |= test_status ))
               fi
             done
-
-            exit "$exit_code"
+            
+            exit $job_status
 
   test-3.6:
     <<: *full-test-template
