Allow unittests to continue running even if one fails
Introduce bug back in to test unittest skip

Add store bad exit codes

Echo exit_code for debugging

Remove subshell and remove indenting only

Return back to parent dir

Add comment and remove echo

Add jsonschema import back in
I had introduced this bug in an earlier commit (in this PR) in order to test whether CircleCI would correctly skip the failed unit test and store its non-zero exit code. Now I am un-doing this bug that I introduced

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -65,18 +65,23 @@ jobs:
           command: |
             shopt -s extglob
 
+            # Loop through unit tests
+            # Note: failed unit tests are skipped. Return the last failed unit
+            #   test exit code once the loop completes.
+            exit_code=0
             for demo in !($IGNORED_DIRS); do
               if [ -d "$demo" ]; then
-                (
-                  env="envs/$demo"
-                  . "$env/bin/activate"
+                env="envs/$demo"
+                . "$env/bin/activate"
 
-                  cd "$demo"
-                  echo "$demo"
-                  coverage run -m unittest discover
-                )
+                cd "$demo"
+                echo "$demo"
+                coverage run -m unittest discover || exit_code=$?
+                cd ..
               fi
             done
+
+            exit $exit_code
 
   test-3.6:
     <<: *full-test-template
